<img src = "./images/cubes.png" alt = "Data Manipulation" width = 800  />

# G01 Data Manipulation using Pandas
**What is the assignment?**
This assignment is a simulation of collaboratively working on a collection of datasets with a group of collaborators in a single notebook. Each one of you will take the ownership of any one set of problems in consultation with your group members. You will solve this assignment in the notebook provided to you in DeepNote or attachment in the brightspace. Please include your name in the heading to indicate the problem solved by you.

**How to seek help?**
a. You can discuss any difficulties you face in solving the problem with your group members.
b. Search for the right command on [Pandas](https://pandas.pydata.org/docs/user_guide/index.html#user-guide)
c. Post your questions on the discussion forum [G01_Data_Manipulation](https://teams.microsoft.com/l/channel/19%3a17275a38fcb94913ab5533f5b7005872%40thread.tacv2/G01%2520Data%2520Manipulation?groupId=67acc077-27df-4ea2-9d16-49eddcc3bbd0&tenantId=244e6ed2-339a-47f3-b95c-e45351c198b7).

**How to Submit?**
a. Each one of you will paste the link to the ipynb notebook in the brightspace as your submission.
b. Attach the ipynb file as attachment in your submission.

**How will you be evaluated?**
You will be graded individually for the part completed by you.
There is **no rubric** for this assignment. 2/3 weightage is for solving the problem and 1/3 for efficiently solving and organizing your solution well following the zen of python principles.

In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!

## Set 1 Automobile Data Set (Group Member 1)

In [2]:
import pandas as pd
import numpy as np
automobile = pd.read_csv("https://raw.githubusercontent.com/dearbharat/pandas/main/automobile.csv")
automobile.head()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

1. Print most expensive car’s company name and price.

2. Display the count of the number of cars for each company.

3. Print the least expensive car in each of the company.

4. Display the number of cars by num-of-cylinders for each body-style.
Hint: Use Group_by or Pivot function

## Set 2 Bank Marketing (Group Member 2)

In [3]:
import pandas as pd
bank = pd.read_csv("https://raw.githubusercontent.com/dearbharat/pandas/main/bank_marketing.csv", nrows=1000)
bank.head(1)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,outcome
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,no

1. Display all the unique values in the column "job".

2. Create a cross table with education as index column, job as columns and mean of age as values.

3. Create a Pivot table of the average of the duration with job as column, marital and housing as index and average of duration as values.

4. Print descriptive statistics of all numerical variables

1. Print descriptive statistics of the categorical columns.

2. Create a separate dataframe of only categorical columns.

3. Display count of customers in a cross tab of InternetService by StreamingMovies

4. Display the average of totalCharges by each paymentMethod for churning and non churning customers

## Set 3 Customer Churn (Group Member 3)

In [4]:
churn = pd.read_csv("https://raw.githubusercontent.com/dearbharat/pandas/main/churn.csv", nrows=1000)
churn.tail(1)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
999,3234-VKACU,Male,0,No,No,2,Yes,No,DSL,No,...,No,Yes,Yes,Yes,Month-to-month,No,Electronic check,70.3,132.4,No

1. Print descriptive statistics of the categorical columns.

2. Create a separate dataframe of only categorical columns.

3. Display count of customers in a cross tab of InternetService by StreamingMovies

4. Display the average of totalCharges by each paymentMethod for churning and non churning customers

## Set 4 IMDB Movies (Group Member 4)

In [5]:
import pandas as pd
IMDB = pd.read_csv("https://raw.githubusercontent.com/dearbharat/pandas/main/IMDB.csv", nrows=1000)
IMDB.head(10)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
5,6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
6,7,La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
7,8,Mindhorn,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,NaN,71.0
8,9,The Lost City of Z,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0
9,10,Passengers,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0

1. Display the list of count of movies for each Director.

2. Display the average Runtime for each Genre. Do not try to normalize the Genre column. Use it as is.

3. Display the top three movies by metascore in each of the year. Display the Title, Director, and Revenue in the output dataframe.

4. Display the number of movies done by each Director in descending order of sum of Revenues.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=0396bd3d-5050-4c7c-9066-8077dbb9bdc2' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>