<img src = "./images/numpy_matplotlib.png" alt = "NumPy Matplotlib" width = 800  />

# G02 NumPy and Matplotlib
In this assignment, you will work collaboratively with your group members to complete tasks listed in this notebook. Each of you will take ownership of any one set and solve it. Any data file required for the assignment is available in the GitHub folder. You are expected to study how other group members solved their set. It will help solve the subsequent I02 assignment. Please include your name in the respective header section to indicate which problem has been solved by you. You can discuss any difficulties you faced in solving the assignment with your group members or post it on the TEAMS.

**How to submit your assignment?**
Each one of you will submit the link to the workspace URL of your group as your submission on the D2L portal.

Note:
You are not required to replicate the text from the links, but a brief description in your own words is expected to describe what you are doing in the code cell.
There is no rubric for this assignment. 2/3 weightage is for solving the problem and 1/3 will be for group performance. Group performance marks are assigned if all members submit their assignment before due the date.
The group performance score component will not be changed even on resubmission so it is collective responsibility of the group to ensure everyone submits their solution before due date.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## Set 1 (First_Name Last_Name)

1. Import the first nine columns of mercedes.csv in a dataframe. Perform one-hot-encoding on 10 most frequent labels in the variables X1 to X6. Label each of the column as variablename_label. For e.g. X1 is a variable with labels a, b, c. Then the one-hot-encoded column names will be X1_a, X1_b, and X1_c
Hint: You will be creating 49 one-hot-encoded variables in total and the final dataframe will have 9 + 49 = 58 columns.

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/dearbharat/datasets/main/mercedes.csv', usecols=['X1', 'X2', 'X3', 'X4', 'X5', 'X6'])
df.head()

  X1  X2 X3 X4 X5 X6
0  v  at  a  d  u  j
1  t  av  e  d  y  l
2  w   n  c  d  x  j
3  t   n  f  d  x  l
4  v   n  f  d  h  d

2. Master the [Masks and Boolean Logic](https://jakevdp.github.io/PythonDataScienceHandbook/02.06-boolean-arrays-and-masks.html) by replicating the numpy array operations here.

In [3]:
rainfall = pd.read_csv('https://raw.githubusercontent.com/dearbharat/datasets/main/Seattle2014.csv')['PRCP'].values
rainfall.shape

(365,)

3. Master the [simple line plots](https://jakevdp.github.io/PythonDataScienceHandbook/04.01-simple-line-plots.html) by replicating the plots here.

4. Master the [Customizing Ticks](https://jakevdp.github.io/PythonDataScienceHandbook/04.10-customizing-ticks.html) by replicating the plots here.

## Set 2 (First_Name Last_Name)

1. Import titanic.csv in a dataframe. Confirm and report any variables  with missing values. Perform the following tasks on the dataframe.
a. For the variable with most missing values create a new column 'variablename_null' with value 1 wherever the value is missing and 0 wherever the record is present in the original variable.
b. For the variable with second highest number of missing values create a new column 'variablename_median' with median replacing the missing values and keep rest of the values as original values.

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/dearbharat/datasets/main/titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

2. Master the [Fancy Indexing](https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html) by replicating the numpy array operations here.

3. Master the [simple scatter plots](https://jakevdp.github.io/PythonDataScienceHandbook/04.02-simple-scatter-plots.html) by replicating the plots here.

4. Master the [Customizing Text and Annotation](https://jakevdp.github.io/PythonDataScienceHandbook/04.09-text-and-annotation.html) by replicating the plots here.

## Set 3 (First_Name Last_Name)

1. Import titanic.csv in a dataframe. Confirm and report any variables  with missing values. Perform the following tasks on the dataframe.
a. For the variable with second highest number of missing values create a new column 'variablename_random' with a random value sampled from variable column. 
b. Repeat this process for all the missing values.

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/dearbharat/datasets/main/titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

2. Master the [Sorting Arrays](https://jakevdp.github.io/PythonDataScienceHandbook/02.08-sorting.html) by replicating the numpy array operations here. 
Note: You do not neeed to complete "Example: k-Nearest Neighbors" section

3. Master the [Density and Contour Plots](https://jakevdp.github.io/PythonDataScienceHandbook/04.04-density-and-contour-plots.html) by replicating the plots here.

4. Master the [Customizing Plot Colorbars](https://jakevdp.github.io/PythonDataScienceHandbook/04.07-customizing-colorbars.html) by replicating the plots here.

## Set 4 (First_Name Last_Name)

1. Import BsmtQual, FireplaceQu, and GarageType variables from loan.csv in a dataframe. Confirm and report the percentage of missing values in each of the variables. Perform the following tasks on the dataframe.
a. In the variables BsmtQual and GarageType, replace the missing values with the most frequently occuring label in the respective variables.
a. In the variable FireplaceQu, replace the missing values with the least frequently occuring label in the variable.

In [6]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/dearbharat/datasets/main/loan.csv', usecols=['BsmtQual', 'FireplaceQu', 'GarageType'])
df.head()

  BsmtQual FireplaceQu GarageType
0       Gd         NaN     Attchd
1       Gd          TA     Attchd
2       Gd          TA     Attchd
3       TA          Gd     Detchd
4       Gd          TA     Attchd

In [7]:
df.isnull().sum()/len(df)

BsmtQual       0.025342
FireplaceQu    0.472603
GarageType     0.055479
dtype: float64

2. Master the [Structured Array](https://jakevdp.github.io/PythonDataScienceHandbook/02.09-structured-data-numpy.html) by replicating the numpy array operations here.

3. Master the [Histograms and Binnings](https://jakevdp.github.io/PythonDataScienceHandbook/04.05-histograms-and-binnings.html) by replicating the plots here.

4. Master the [Customizing Plot Legends](https://jakevdp.github.io/PythonDataScienceHandbook/04.06-customizing-legends.html) by replicating the plots here.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=0396bd3d-5050-4c7c-9066-8077dbb9bdc2' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>